# Authors: Arnar Jónsson and Hólmsteinn Orri Egilsson.
# Doc strings generated by ChatGPT and Github Copilot.
# Some code snippets written by Github Copilot, but the design and overall structure and logic is by the authors.

from ple.games.flappybird import FlappyBird
from ple import PLE
import numpy as np
from collections import deque
import torch
import torch.nn as nn
import torch.optim as optim
import time
import copy

class ReplayBuffer:
    """
    A buffer to store and sample experiences for reinforcement learning.
    Attributes:
        capacity (int): Maximum number of experiences to store in the buffer.
        sample_size (int): Number of experiences to sample from the buffer.
    Methods:
        push(experience): Adds an experience to the buffer.
        sample(): Samples a batch of experiences from the buffer.
        __len__(): Returns the current number of experiences in the buffer.
    """
    def __init__(self, capacity, sample_size):
        self.buffer = deque(maxlen=capacity)
        self.capacity = capacity
        self.sample_size = sample_size
    
    def push(self, experience):
        self.buffer.append(experience)
    
    def sample(self):
        indices = np.random.choice(len(self.buffer), self.sample_size, replace=False)
        states, actions, rewards, next_states, dones = zip(*[self.buffer[idx] for idx in indices])
        return np.array(states), np.array(actions), np.array(rewards), np.array(next_states), np.array(dones)
    
    def __len__(self):
        return len(self.buffer)
    

class NeuralNetwork(nn.Module):
    """
    A simple feedforward neural network with two hidden layers.
    Attributes:
        fc1 (nn.Linear): First fully connected layer.
        fc2 (nn.Linear): Second fully connected layer.
        fc3 (nn.Linear): Output fully connected layer.
        optimizer (optim.AdamW): Optimizer for training the network.
        criterion (nn.MSELoss): Loss function for training the network.
    Methods:
        forward(x):
            Performs a forward pass through the network.
        partial_fit(X, y):
            Performs a single training step using the provided input and target output.
    """

    def __init__(self, input_dim, output_dim, alpha=0.001):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(input_dim, 10)
        self.fc2 = nn.Linear(10, 10)
        self.fc3 = nn.Linear(10, output_dim)

        self.optimizer = optim.AdamW(self.parameters(), lr=alpha)
        self.criterion = nn.MSELoss()
    
    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def partial_fit(self, X, y):
        self.optimizer.zero_grad()
        output = self.forward(X)
        loss = self.criterion(output, y)
        loss.backward()
        self.optimizer.step()

class FlappyAgent:
    def __init__(self, alpha=0.001, epsilon=0.1, epsilon_decay=[False], soft_update=[False]):
        """
        Initialize the Flappy Agent with specified parameters.
        Parameters:
        alpha (float): Learning rate for the neural network.
        epsilon (float): Initial exploration rate for epsilon-greedy policy.
        epsilon_decay (list): List containing boolean flag for epsilon decay and decay parameters.
        soft_update (list): List containing boolean flag for soft update and tau parameter.
        Initializes neural networks, replay buffer, and various parameters for training.
        """

        # Networks
        self.decision_network = NeuralNetwork(4, 2, alpha)
        self.target_network = copy.deepcopy(self.decision_network)

        # Replay Buffer
        self.replay_buffer = ReplayBuffer(10000,100)

        # Parameters
        self.alpha = alpha
        if epsilon_decay[0]:
            self.epsilon_decay = True
            self.epsilon = epsilon_decay[1]
            self.epsilon_decay_rate = epsilon_decay[2]
            self.min_epsilon = epsilon_decay[3]
        else:
            self.epsilon_decay = False
            self.epsilon = epsilon
        if soft_update[0]:
            self.soft_update = True
            self.tau = soft_update[1]
        else:
            self.soft_update = False

        # Counters
        self.train_count = 0
        self.learning_curve = []
        self.std_curve = []
        self.test_scores = []	

        # Constants
        HEIGHT = 512
        FLOOR = 130
        GAP_SIZE = 100

        self.MAX_Y = HEIGHT - FLOOR # the floor is 130
        self.MIN_Y = 0
        self.MAX_DX = 309
        self.MIN_DX = 0
        self.MAX_DY = HEIGHT - FLOOR - GAP_SIZE # 100 is the gap_size
        self.MIN_DY = 0
        self.MAX_V = 10
        self.MIN_V = -8
        
        # Print confirmation
        print('Flappy Agent Initialized')
        print('Doing Deep Q Learning with:')
        print(f'    Alpha: {alpha}')
        if self.epsilon_decay:
            print(f'    Epsilon decay: {self.epsilon_decay}, Epsilon: {self.epsilon}, Min epsilon: {self.min_epsilon}, Epsilon decay rate: {self.epsilon_decay_rate}')
        else:
            print(f'    Epsilon decay: {self.epsilon_decay}, Epsilon: {self.epsilon}')
        if self.soft_update:
            print(f'    Soft update: {self.soft_update}, Tau: {self.tau}')
        else:
            print(f'    Soft update: {self.soft_update}')

    def normalize(self, state):
        """
        Normalize the game state values to a range of [-1, 1].
        Parameters:
        state (dict): A dictionary containing the current game state with keys:
            - 'player_y': The y-coordinate of the player.
            - 'next_pipe_dist_to_player': The distance to the next pipe.
            - 'next_pipe_top_y': The y-coordinate of the top of the next pipe.
            - 'player_vel': The velocity of the player.
        Returns:
        np.array: A numpy array of normalized state values.
        """

        return np.array([
            (state['player_y'] - self.MIN_Y-1) / (self.MAX_Y - self.MIN_Y) * 2 - 1,
            (state['next_pipe_dist_to_player'] - self.MIN_DX-1) / (self.MAX_DX - self.MIN_DX) * 2 - 1,
            (state['next_pipe_top_y'] - self.MIN_DY-1) / (self.MAX_DY - self.MIN_DY) * 2 - 1,
            (max(min(self.MAX_V, state['player_vel']), self.MIN_V) - self.MIN_V) / (self.MAX_V - self.MIN_V) * 2 - 1
        ])
    
    def update_epsilon(self):
        """
        Update the epsilon value by decaying it according to the epsilon decay rate,
        ensuring it does not fall below the minimum epsilon value.
        """

        self.epsilon = max(self.min_epsilon, self.epsilon * self.epsilon_decay_rate)

    def observe(self, normS1, action, reward, normS2, end):
        """
        Store the experience in the replay buffer and update the decision network.
        Args:
            normS1 (array-like): Normalized state before the action.
            action (int): Action taken by the agent.
            reward (float): Reward received after taking the action.
            normS2 (array-like): Normalized state after the action.
            end (bool): Whether the episode has ended.
        """

        self.replay_buffer.push((normS1, action, reward, normS2, end))
        self.update_decision_network()

    def update_decision_network(self):
        """
        Updates the decision network using experiences from the replay buffer.
        """

        if len(self.replay_buffer) < self.replay_buffer.sample_size:
            return

        normS1, actions, rewards, normS2, ends = self.replay_buffer.sample()
        
        network_q_values = self.decision_network.forward(torch.tensor(normS1.astype(np.float32)))
        with torch.no_grad():
            next_q_values = self.target_network.forward(torch.tensor(normS2[~ends].astype(np.float32))).numpy()
        target_q_values = copy.deepcopy(network_q_values.detach().numpy())

        target_q_values[~ends, actions[~ends]] = rewards[~ends] + np.max(next_q_values, axis=1)
        target_q_values[ends, actions[ends]] = rewards[ends]
        
        target_q_values = torch.tensor(target_q_values)

        self.decision_network.partial_fit(torch.tensor(normS1.astype(np.float32)), target_q_values)

        self.train_count += 1
        self.update_target_network()
    
    def update_target_network(self):
        """
        Update the target network with the parameters from the decision network.
        If soft_update is enabled, perform a soft update of the target network parameters.
        Otherwise, update the target network every 100 training steps.
        """

        if self.soft_update:
            for target_param, decision_param in zip(self.target_network.parameters(), self.decision_network.parameters()):
                target_param.data.copy_(self.tau * decision_param.data + (1 - self.tau) * target_param.data)
        elif self.train_count % 100 == 0:
            self.target_network.load_state_dict(self.decision_network.state_dict())

    def training_policy(self, normS):
        """
        Selects an action based on the epsilon-greedy policy.
        Parameters:
        normS (numpy.ndarray): The normalized state representation.
        Returns:
        int: The selected action (0 or 1).
        """

        if np.random.rand() < self.epsilon:
            return np.random.choice([0, 1])
        else:
            with torch.no_grad():
                return self.decision_network.forward(torch.tensor(normS.astype(np.float32))).argmax().item()
        
    def reward_values(self):
        """
        Returns a dictionary of reward values for different game events.
        """

        return {"positive": 1.0, "tick": 0.0, "loss": -5.0}
    
    def policy(self, normS):
        """
        Selects an action based on the given normalized state using the decision network.
        """

        with torch.no_grad():
            return self.decision_network.forward(torch.tensor(normS.astype(np.float32))).argmax().item()
    
def train(nb_episodes, agent, time_limit=None, display_screen=False, force_fps=True, learning_curve=False):
    """
    Train the agent using Deep Q-Learning.
    Parameters:
    nb_episodes (int): Number of episodes to train the agent.
    agent (object): The agent to be trained.
    time_limit (int, optional): Time limit for training in seconds. Defaults to None.
    display_screen (bool, optional): Whether to display the game screen during training. Defaults to False.
    force_fps (bool, optional): Whether to force the frames per second. Defaults to True.
    learning_curve (bool, optional): Whether to track the learning curve. Defaults to False.
    """

    reward_values = agent.reward_values()
    env_train = PLE(FlappyBird(), fps=30, display_screen=display_screen, force_fps=force_fps, rng=None, reward_values=reward_values)
    env_train.init()

    nb_episode = 0
    nb_frames = 0

    if time_limit != None:
        stop_time = time.time() + time_limit
        time_limit = True
    
    while nb_episode <= nb_episodes:
        state = env_train.game.getGameState()
        normS1 = agent.normalize(state)
        action = agent.training_policy(normS1)
        if agent.epsilon_decay:
            agent.update_epsilon()

        reward = env_train.act(env_train.getActionSet()[action])
        newState = env_train.game.getGameState()
        normS2 = agent.normalize(newState)
        agent.observe(normS1, action, reward, normS2, env_train.game_over())

        nb_frames += 1

        if learning_curve and nb_frames == 10000:
            run_game(10, agent, print_progress=False)  
            agent.learning_curve.append(np.mean(agent.test_scores))
            agent.std_curve.append(np.std(agent.test_scores))
            nb_frames = 0

        if env_train.game_over():
    
            env_train.reset_game()
            nb_episode += 1
            
            if nb_episode % 100 == 0:
                print(f'Episode {nb_episode} completed')

            if time_limit and time.time() > stop_time:
                break

def run_game(nb_episodes, agent, display_screen=False, force_fps=True, print_progress=True):
    """
    Run the Flappy Bird game for a specified number of episodes using a given agent.
    Parameters:
    nb_episodes (int): Number of episodes to run the game.
    agent (object): The agent that will play the game.
    display_screen (bool, optional): Whether to display the game screen. Default is False.
    force_fps (bool, optional): Whether to force the frames per second. Default is True.
    print_progress (bool, optional): Whether to print progress every 100 episodes. Default is True.
    """

    reward_values = {"positive": 1.0, "negative": 0.0, "tick": 0.0, "loss": 0.0, "win": 0.0}

    env = PLE(FlappyBird(), fps=30, display_screen=display_screen, force_fps=force_fps, rng=None, reward_values=reward_values)
    env.init()

    nb_episode = 0
    score = 0

    agent.test_scores = []
    while nb_episode <= nb_episodes:
        state = env.game.getGameState()
        normS = agent.normalize(state)
        action = agent.policy(normS)

        reward = env.act(env.getActionSet()[action])
        score += reward
        
        if env.game_over():
            env.reset_game()
            nb_episode += 1
            agent.test_scores.append(score)
            score = 0
            if print_progress and nb_episode % 100 == 0:
                print(f'Episode {nb_episode} completed')



    
